### ISSUE TITLE
Extract timestamps

### ISSUE THREAD

**Issue by tneg** [QuantumPhotonicsLab/readPTU#1]
Is there a way to extract the raw timestamps from a .ptu file without any binning?

**Comment by raphaelproux** [comment]
Hi tneg,
You cannot do that with the current version of the library. It could relatively easily be implemented but the main interest of the library is to do the analyses on the fly, reading directly the ptu file. Also it can generate a huge amount of data if not handled properly. Anyway, I think it could be interesting to have the feature. I don't have time to look into it right now but you are welcome to try, of course :)

**Comment by snizzleorg** [comment]
You can use the demo source for that: https://github.com/PicoQuant/PicoQuant-Time-Tagged-File-Format-Demos

**Comment by raphaelproux** [comment]
Indeed you can have a look at the PicoQuant demo code – I am happy to see some Python there!
However, it might be a bit slow. Our library has the advantage of providing a Python interface with some compiled C behind to make the whole file read/processing much much faster (several orders of magnitude faster). Basically, it will depend on how many events you have recorded in your ptu file...
